### ISSUE TITLE
Compile error with gcc 10

### ISSUE THREAD

**Issue by ioerror** [JJChiDguez/csidh#3]
Using Ubuntu 20.04 with gcc 9 (gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)) to compile csidh works as expected. With 20.10, Ubuntu moved to gcc 10 (gcc version 10.2.0 (Ubuntu 10.2.0-13ubuntu1)) and it now has the following build issues:
```
$ make csidh BITLENGTH_OF_P=512 TYPE=DUMMYFREE
gcc -I./inc -I./inc/fp512/ ./lib/rng.c ./lib/fp512.S ./lib/point_arith.c ./lib/isogenies.c ./lib/action_simba_dummyfree.c ./main/csidh.c -o ./bin/csidh -O3 -funroll-loops -fomit-frame-pointer -m64 -mbmi2 -DFP_512 -DDUMMYFREE 
/usr/bin/ld: /tmp/cckT7P67.o:(.bss+0x0): multiple definition of `FP_MUL_COMPUTED'; /tmp/ccMlTZm7.o:(.bss+0x0): first defined here
/usr/bin/ld: /tmp/cckT7P67.o:(.bss+0x8): multiple definition of `FP_SQR_COMPUTED'; /tmp/ccMlTZm7.o:(.bss+0x8): first defined here
/usr/bin/ld: /tmp/cckT7P67.o:(.bss+0x10): multiple definition of `FP_ADD_COMPUTED'; /tmp/ccMlTZm7.o:(.bss+0x10): first defined here
/usr/bin/ld: /tmp/ccOoL0h8.o:(.bss+0x0): multiple definition of `FP_MUL_COMPUTED'; /tmp/ccMlTZm7.o:(.bss+0x0): first defined here
/usr/bin/ld: /tmp/ccOoL0h8.o:(.bss+0x8): multiple definition of `FP_SQR_COMPUTED'; /tmp/ccMlTZm7.o:(.bss+0x8): first defined here
/usr/bin/ld: /tmp/ccOoL0h8.o:(.bss+0x10): multiple definition of `FP_ADD_COMPUTED'; /tmp/ccMlTZm7.o:(.bss+0x10): first defined here
/usr/bin/ld: /tmp/cc1Z7My8.o:(.bss+0x10): multiple definition of `FP_ADD_COMPUTED'; /tmp/ccMlTZm7.o:(.bss+0x10): first defined here
/usr/bin/ld: /tmp/cc1Z7My8.o:(.bss+0x8): multiple definition of `FP_SQR_COMPUTED'; /tmp/ccMlTZm7.o:(.bss+0x8): first defined here
/usr/bin/ld: /tmp/cc1Z7My8.o:(.bss+0x0): multiple definition of `FP_MUL_COMPUTED'; /tmp/ccMlTZm7.o:(.bss+0x0): first defined here
collect2: error: ld returned 1 exit status
make: *** [Makefile:49: csidh] Error 1
```

One simple solution for others to complete a build on Ubuntu 20.10 is to set `CC=gcc-9` explicitly until the code has been ported to gcc 10. Another quick fix to make build work again with gcc 10 is to add `-fcommon` to CFLAGS as this returns to the default behavior of gcc 9. The flag `-fno-common` is the new [gcc 10 default](https://gcc.gnu.org/gcc-10/porting_to.html).

I've opened a pull request (#2) to apply the quick fix to return to the behavior under gcc 9 when building with gcc 10. A better solution would be to use extern as the gcc 10 porting page explains.

**Comment by JJChiDguez** [comment]
Hi!
Thank you very much for catching this issue!

I promise to check it (and include your pull request), in this week.

Sorry for the late reply (I don't know why I didn't receive any notification about this issue [neither the pull request])

However, I will come back later at night to check and proceed with the issue and then fix it with your pull request.

By the way, if you have interest on CSIDH using the new fast isogeny formulae, then I suggest to check the repo THE SQALE OF CSIDH (in that implementation which is more ordered and updated, one can run large CSIDH isntantiations... I infer your interesting comments and pull request could be useful for that project).

Best, Jesús.
